---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service # Note that this *must* be the same as the service name, or this won't work!
subsets:
  - addresses:
      - ip: 10.132.32.223
    ports:
      - port: 8082